import json
from pathlib import Path

cells = [
    # Cell 1: Intro
    {
        "cell_type": "markdown",
        "id": "intro-step2",
        "metadata": {},
        "source": [
            "# Step 2: Java Source Code Translation (Layer 2 & 3 Consolidated)\n",
            "\n",
            "This notebook simulates and prototypes the code refactoring process on the `working/sonar-stash` project codebase.\n",
            "\n",
            "This step focuses on:\n",
            "- Detecting JDK 17 deprecated/removed APIs (Layer 2) using `jdeprscan`.\n",
            "- Collecting compilation errors under JDK 17 (Layer 3) using `mvn compile`.\n",
            "- Bundling findings by file and querying local Ollama LLM to refactor using a list of non-overlapping block edits applied from bottom to top."
        ]
    },
    # Cell 2: Setup Paths and Project Root
    {
        "cell_type": "code",
        "execution_count": None,
        "id": "setup-paths-step2",
        "metadata": {},
        "outputs": [],
        "source": [
            "import sys\n",
            "import os\n",
            "import json\n",
            "from pathlib import Path\n",
            "\n",
            "# Ensure project root is in sys.path\n",
            "PROJECT_ROOT = Path.cwd().resolve()\n",
            "if str(PROJECT_ROOT) not in sys.path:\n",
            "    sys.path.append(str(PROJECT_ROOT))\n",
            "\n",
            "print(f\"Project root added to path: {PROJECT_ROOT}\")\n",
            "\n",
            "# Check availability of key imports\n",
            "from src.tools.maven import MavenProject, MavenPomEditor, MavenRunner\n",
            "from src.core.tree_sitter_engine import UniversalASTReader\n",
            "from src.tools.codebase_search_tools import find_code_usages, search_codebase\n",
            "\n",
            "print(\"Successfully imported models and tools!\")\n",
            "\n",
            "# Setup paths globally (Adjust PROJECT_PATH to point to your target Java project)\n",
            "PROJECT_PATH = Path(\"working/sonar-stash\").resolve()\n",
            "pom_path = PROJECT_PATH / \"pom.xml\"\n",
            "ARTIFACTS_DIR = PROJECT_PATH / \"artifacts\"\n",
            "\n",
            "review_file = ARTIFACTS_DIR / \"reader_review.json\"\n",
            "if not review_file.exists():\n",
            "    review_file = Path(\"dependency_focus_scopes.json\").resolve()\n",
            "\n",
            "print(f\"Working Project path: {PROJECT_PATH} (exists: {PROJECT_PATH.exists()})\")\n",
            "print(f\"Artifacts path: {ARTIFACTS_DIR}\")\n",
            "print(f\"Review report path: {review_file} (exists: {review_file.exists()})\")"
        ]
    },
    # Cell 3: Load Reports
    {
        "cell_type": "code",
        "execution_count": None,
        "id": "load-reports-step2",
        "metadata": {},
        "outputs": [],
        "source": [
            "# Load POM upgrade results from POM migration phase\n",
            "review_data = {}\n",
            "selected_sol = {}\n",
            "\n",
            "if review_file.exists():\n",
            "    with open(review_file, \"r\", encoding=\"utf-8\") as f:\n",
            "        review_data = json.load(f)\n",
            "    review_body = review_data.get(\"review_upgrade_candidates\", {})\n",
            "    selected_sol = review_body.get(\"selected_solution\", {})\n",
            "    print(\"Upgraded Dependency Mappings (from reader_review.json):\")\n",
            "    print(json.dumps(selected_sol, indent=2))\n",
            "else:\n",
            "    print(\"reader_review.json not found!\")"
        ]
    },
    # Cell 4: Markdown Section Intro
    {
        "cell_type": "markdown",
        "id": "scan-section-desc",
        "metadata": {},
        "source": [
            "## 1. Consolidated Compilation & Deprecated API Scan\n",
            "\n",
            "We run JDK 17 compilation to get modern compiler errors and execute `jdeprscan` to capture deprecated/removed API usages. These are aggregated by Java source file."
        ]
    },
    # Cell 5: Run Scan & Rule Matching
    {
        "cell_type": "code",
        "execution_count": None,
        "id": "consolidated-scan",
        "metadata": {},
        "outputs": [],
        "source": [
            "from src.tools.maven import MavenRunner, MavenProject\n",
            "from src.tools.jdeprscan_pipeline import run_jdeprscan_pipeline\n",
            "import re\n",
            "\n",
            "# 1. Compile project under JDK 17 once to extract initial compile errors\n",
            "print(\"Compiling project under JDK 17...\")\n",
            "runner = MavenRunner(target_java_version=\"17\")\n",
            "compile_res = runner.compile(PROJECT_PATH, clean=True)\n",
            "print(f\"Initial compile status: {compile_res.status}\")\n",
            "\n",
            "# 2. Run jdeprscan pipeline under JDK 17 to detect deprecated/removed APIs (Level 2)\n",
            "print(\"Running jdeprscan pipeline on the working codebase...\")\n",
            "updated_jdeprscan_result = run_jdeprscan_pipeline(\n",
            "    project_path=str(PROJECT_PATH),\n",
            "    target_release=\"17\",\n",
            "    logger=lambda msg: print(f\"  {msg}\")\n",
            ")\n",
            "\n",
            "file_findings = {}\n",
            "\n",
            "# Helper function to extract compile errors from maven stdout/stderr output without using fragile regex\n",
            "def extract_file_errors(compile_output, project_path):\n",
            "    findings = []\n",
            "    lines = compile_output.splitlines()\n",
            "    i = 0\n",
            "    while i < len(lines):\n",
            "        line = lines[i]\n",
            "        if \"[ERROR]\" in line and \".java\" in line:\n",
            "            parts = line.split(\".java\")\n",
            "            if len(parts) >= 2:\n",
            "                path_part = parts[0].strip()\n",
            "                if path_part.startswith(\"[ERROR]\"):\n",
            "                    path_part = path_part[len(\"[ERROR]\"):].strip()\n",
            "                if path_part.startswith(\"/\") and len(path_part) > 2 and path_part[2] == \":\":\n",
            "                    path_part = path_part[1:]\n",
            "                \n",
            "                abs_path = Path(path_part + \".java\")\n",
            "                try:\n",
            "                    rel_path = abs_path.relative_to(project_path)\n",
            "                except ValueError:\n",
            "                    if \"src/\" in path_part:\n",
            "                        rel_path = Path(\"src/\" + path_part.split(\"src/\", 1)[1] + \".java\")\n",
            "                    elif \"src\\\\\" in path_part:\n",
            "                        rel_path = Path(\"src/\" + path_part.split(\"src\\\\\", 1)[1].replace(\"\\\\\", \"/\") + \".java\")\n",
            "                    else:\n",
            "                        rel_path = abs_path\n",
            "                \n",
            "                standard_path = str(rel_path).replace(\"\\\\\", \"/\")\n",
            "                details = parts[1].strip()\n",
            "                \n",
            "                line_match = re.search(r'\\d+', details)\n",
            "                line_no = line_match.group(0) if line_match else \"unknown\"\n",
            "                \n",
            "                msg = details\n",
            "                if msg.startswith(\":\"):\n",
            "                    msg = msg[1:].strip()\n",
            "                if msg.startswith(\"[\") and \"]\" in msg:\n",
            "                    msg = msg.split(\"]\", 1)[1].strip()\n",
            "                if line_no != \"unknown\" and msg.startswith(line_no):\n",
            "                    msg = msg[len(line_no):].strip()\n",
            "                if msg.startswith(\":\"):\n",
            "                    msg = msg[1:].strip()\n",
            "                if msg.lower().startswith(\"error:\"):\n",
            "                    msg = msg[6:].strip()\n",
            "                if msg.startswith(\":\"):\n",
            "                    msg = msg[1:].strip()\n",
            "                \n",
            "                # Look ahead for symbol: and location: detail lines\n",
            "                detail_lines = []\n",
            "                j = i + 1\n",
            "                while j < len(lines):\n",
            "                    next_line = lines[j]\n",
            "                    if \"[ERROR]\" in next_line and (\"symbol:\" in next_line or \"location:\" in next_line):\n",
            "                        detail_lines.append(next_line.replace(\"[ERROR]\", \"\").strip())\n",
            "                        j += 1\n",
            "                    else:\n",
            "                        break\n",
            "                \n",
            "                if detail_lines:\n",
            "                    msg = f\"{msg} | \" + \" | \".join(detail_lines)\n",
            "                    i = j - 1  # Advance index to the last processed detail line\n",
            "                \n",
            "                findings.append((standard_path, line_no, msg))\n",
            "        i += 1\n",
            "    return findings\n",
            "\n",
            "# Parse errors from JDK 17 compilation\n",
            "compile_errors_matched = extract_file_errors(compile_res.stdout + \"\\n\" + compile_res.stderr, PROJECT_PATH)\n",
            "print(f\"\\nExtracted {len(compile_errors_matched)} compile error(s) under JDK 17:\")\n",
            "for standard_path, line_no, err_msg in compile_errors_matched:\n",
            "    file_findings.setdefault(standard_path, {\"findings\": [], \"matching_rules\": []})\n",
            "    file_findings[standard_path][\"findings\"].append(f\"Compile Error (Line {line_no}): {err_msg}\")\n",
            "    print(f\"  * {standard_path}:{line_no} -> {err_msg}\")\n",
            "\n",
            "# Parse compile errors from jdeprscan b1 step (runs JDK 8 compile as part of scan pipeline)\n",
            "b1_step = updated_jdeprscan_result.get(\"steps\", {}).get(\"b1_compile\", {})\n",
            "if b1_step.get(\"status\") == \"FAIL\":\n",
            "    b1_error = b1_step.get(\"error\", \"\")\n",
            "    b1_matches = extract_file_errors(b1_error, PROJECT_PATH)\n",
            "    for standard_path, line_no, err_msg in b1_matches:\n",
            "        file_findings.setdefault(standard_path, {\"findings\": [], \"matching_rules\": []})\n",
            "        file_findings[standard_path][\"findings\"].append(f\"Compile Error (Line {line_no}): {err_msg}\")\n",
            "\n",
            "# Parse jdeprscan B2 project scan warnings/removal items\n",
            "b2_step = updated_jdeprscan_result.get(\"steps\", {}).get(\"b2_project_scan\", {})\n",
            "for line in b2_step.get(\"for_removal\", []) + b2_step.get(\"deprecated\", []):\n",
            "    m = re.match(r\"class\\s+([^\\s]+)\\s+uses\", line)\n",
            "    if m:\n",
            "        class_path = m.group(1)\n",
            "        rel_path = f\"src/main/java/{class_path}.java\"\n",
            "        file_findings.setdefault(rel_path, {\"findings\": [], \"matching_rules\": []})\n",
            "        file_findings[rel_path][\"findings\"].append(f\"Jdeprscan warning: {line}\")\n",
            "\n",
            "# Parse reader review flagged risks\n",
            "if review_file.exists():\n",
            "    review_body = review_data.get(\"review_upgrade_candidates\", {})\n",
            "    risks_data = review_body.get(\"risks\", \"\")\n",
            "    risks_text = \" \".join(risks_data) if isinstance(risks_data, list) else str(risks_data)\n",
            "    candidates = re.findall(r\"\\b(?:javax\\.\\w+|com\\.sun\\.\\w+)\\b\", risks_text)\n",
            "    for cand in candidates:\n",
            "        matches = search_codebase(\n",
            "            project_path=str(PROJECT_PATH),\n",
            "            regex_pattern=r\"import\\s+\" + cand.replace(\".\", r\"\\.\"),\n",
            "            file_extensions=[\"java\"]\n",
            "        )\n",
            "        for m in matches:\n",
            "            rel_path = m[\"file_path\"].replace(\"\\\\\", \"/\")\n",
            "            file_findings.setdefault(rel_path, {\"findings\": [], \"matching_rules\": []})\n",
            "            file_findings[rel_path][\"findings\"].append(f\"Reader review flagged risk: usage of {cand}\")\n",
            "\n",
            "# Deduplicate findings per file\n",
            "for path, info in file_findings.items():\n",
            "    info[\"findings\"] = list(set(info[\"findings\"]))\n",
            "\n",
            "# Load rules and match them against findings and codebase contents\n",
            "rules_file = Path(\"migration_rules.json\")\n",
            "rules = []\n",
            "if rules_file.exists():\n",
            "    with open(rules_file, \"r\", encoding=\"utf-8\") as f:\n",
            "        rules = json.load(f).get(\"rules\", [])\n",
            "\n",
            "for rel_path, info in file_findings.items():\n",
            "    full_path = PROJECT_PATH / rel_path\n",
            "    if not full_path.exists():\n",
            "        continue\n",
            "    file_content = full_path.read_text(errors=\"ignore\")\n",
            "    for rule in rules:\n",
            "        target = rule.get(\"target\")\n",
            "        if target:\n",
            "            is_match = False\n",
            "            for fnd in info[\"findings\"]:\n",
            "                if target in fnd:\n",
            "                    is_match = True\n",
            "                    break\n",
            "            if not is_match:\n",
            "                if rule.get(\"type\") == \"import_declaration\":\n",
            "                    if f\"import {target}\" in file_content:\n",
            "                        is_match = True\n",
            "                else: \n",
            "                    target_short = target.split()[-1].split(\"(\")[0]\n",
            "                    if target_short in file_content:\n",
            "                        is_match = True\n",
            "            if is_match and rule not in info[\"matching_rules\"]:\n",
            "                info[\"matching_rules\"].append(rule)\n",
            "\n",
            "print(f\"\\nFound {len(file_findings)} file(s) requiring translation:\")\n",
            "for path, info in file_findings.items():\n",
            "    print(f\"\\n- File: {path}\")\n",
            "    print(f\"  Findings:\")\n",
            "    for fnd in info[\"findings\"]:\n",
            "        print(f\"    * {fnd}\")\n",
            "    print(f\"  Matching Rules:\")\n",
            "    for r in info[\"matching_rules\"]:\n",
            "        print(f\"    * [{r.get('rule_id')}] {r.get('target')} -> {r.get('new')} ({r.get('reason')})\")\n",
            "\n",
            "# Save diagnostic reports to target/ and artifacts/ so the agent can load them\n",
            "for folder in [\"artifacts\", \"target\"]:\n",
            "    dir_path = PROJECT_PATH / folder\n",
            "    dir_path.mkdir(parents=True, exist_ok=True)\n",
            "    with open(dir_path / \"jdeprscan_report.json\", \"w\", encoding=\"utf-8\") as f:\n",
            "        json.dump(updated_jdeprscan_result, f, indent=2, default=str)\n",
            "    change_candidates = []\n",
            "    for f_path, f_info in file_findings.items():\n",
            "        change_candidates.append({\n",
            "            \"file_path\": f_path,\n",
            "            \"reason\": \"; \".join(f_info[\"findings\"]),\n",
            "            \"matching_rules\": f_info[\"matching_rules\"]\n",
            "        })\n",
            "    mygrate_report = {\n",
            "        \"status\": \"ok\",\n",
            "        \"change_candidates\": change_candidates\n",
            "    }\n",
            "    with open(dir_path / \"mygrate_report.json\", \"w\", encoding=\"utf-8\") as f:\n",
            "        json.dump(mygrate_report, f, indent=2, default=str)\n",
            "print(\"\\nSuccessfully saved jdeprscan_report.json and mygrate_report.json to target/ and artifacts/!\")\n"
        ]
    },
    # Cell 6: Markdown Translation Intro
    {
        "cell_type": "markdown",
        "id": "translation-section-desc",
        "metadata": {},
        "source": [
            "## 2. Iterative Translation Loop\n",
            "\n",
            "We run a focused code translation loop to resolve JDK 17 migration blockers file-by-file.\n",
            "For each file, we call ChatOllama directly to refactor code, apply the modified source, and check the Maven compilation status to verify correctness."
        ]
    },
    # Cell 7: Import TranslatorAgent_2
    {
        "cell_type": "code",
        "execution_count": None,
        "id": "define-translator-agent-2",
        "metadata": {},
        "outputs": [],
        "source": [
            "from src.agents.translator_agent_2 import TranslatorAgent_2\n",
            "print(\"TranslatorAgent_2 class imported successfully from src.agents.translator_agent_2!\")\n"
        ]
    },
    # Cell 8: Unified Main Source & Test Translation Loop (Alternate Strategy)
    {
        "cell_type": "code",
        "execution_count": None,
        "id": "unified-translation-loop",
        "metadata": {},
        "outputs": [],
        "source": [
            "import json\n",
            "from pathlib import Path\n",
            "from datetime import datetime\n",
            "\n",
            "LOG_FILE = Path(\"log.txt\")\n",
            "\n",
            "print(\"=== STARTING UNIFIED TRANSLATION LOOP (MAIN & TESTS ALTERNATING MODE) ===\")\n",
            "print(\"Strategy: The agent will resolve errors in both main source and tests. Code Lock will auto-unlock if main errors recur.\")\n",
            "\n",
            "from src.tools.maven import MavenRunner\n",
            "runner = MavenRunner(target_java_version=\"17\")\n",
            "\n",
            "# Perform initial scan of tests to see full status\n",
            "compile_res = runner.test(PROJECT_PATH, skip_tests=False, clean=True)\n",
            "compile_output = compile_res.stdout + \"\\n\" + compile_res.stderr\n",
            "\n",
            "filtered_lines = []\n",
            "for line in compile_output.splitlines():\n",
            "    if len(line) > 800 or \"-classpath\" in line or \" -d \" in line or \"-bootclasspath\" in line:\n",
            "        continue\n",
            "    filtered_lines.append(line)\n",
            "if len(filtered_lines) > 150:\n",
            "    truncated_compile_output = (\n",
            "        \"\\n\".join(filtered_lines[:75]) +\n",
            "        \"\\n... [TRUNCATED IN-BETWEEN LINES / CLASS PATH / DEBUG INFOS TO SAVE CONTEXT] ...\\n\" +\n",
            "        \"\\n\".join(filtered_lines[-75:])\n",
            "    )\n",
            "else:\n",
            "    truncated_compile_output = \"\\n\".join(filtered_lines)\n",
            "\n",
            "print(f\"\\nInitial Maven verification status (test phase): {compile_res.status}\")\n",
            "if compile_res.status == 0:\n",
            "    print(\"✓ Project already compiles and tests pass under JDK 17!\")\n",
            "else:\n",
            "    payload = {\n",
            "        \"project_path\": str(PROJECT_PATH),\n",
            "        \"target_java_version\": \"17\",\n",
            "        \"current_instruction\": (\n",
            "            \"Migrate the project to JDK 17 and new SonarQube API.\\n\"\n",
            "            \"You must solve BOTH production code (src/main/java) compilation errors and test code (src/test/java) compilation/runtime failures.\\n\\n\"\n",
            "            \"RAG GUIDELINE:\\n\"\n",
            "            \"- Open and read the `migration_rules.json` file in the project root. It contains specific migration recipes and rules for upgraded libraries and API changes.\\n\"\n",
            "            \"- You MUST follow the exact requirements and examples defined in `migration_rules.json` when migrating library usages.\\n\\n\"\n",
            "            \"Work flow:\\n\"\n",
            "            \"1. Run compile_project(run_tests=false) to check and fix main source first.\\n\"\n",
            "            \"2. Once main source compiles, run compile_project(run_tests=true) to check and fix tests.\\n\"\n",
            "            \"3. If test compile fails because of a newly introduced issue in main source, the Code Lock will automatically unlock so you can fix main source again.\\n\"\n",
            "            \"4. Repeat this process until all tests pass.\\n\\n\"\n",
            "            \"CRITICAL RULES:\\n\"\n",
            "            \"- NO REWARD HACKING: Do not skip tests, comment out asserts, delete test methods, or use @Ignore/@Disabled.\\n\"\n",
            "            \"- Verify every single edit by calling compile_project.\\n\"\n",
            "            \"- Pay attention to the logs which indicate whether [CODE LOCK] is active or has dynamically unlocked.\"\n",
            "        ),\n",
            "        \"findings\": truncated_compile_output,\n",
            "        \"rules\": \"\"\n",
            "    }\n",
            "\n",
            "    agent = TranslatorAgent_2()\n",
            "    # Set Agent maximum iterations to 80\n",
            "    agent.MAX_ITERATIONS = 80\n",
            "    \n",
            "    result = agent.run(json.dumps(payload, ensure_ascii=False, indent=2))\n",
            "\n",
            "    with open(LOG_FILE, \"a\", encoding=\"utf-8\") as f:\n",
            "        f.write(f\"\\n{'='*80}\\n\")\n",
            "        f.write(\"PHASE 2 — UNIFIED MIGRATION & TEST FIXES (ALT MODE)\\n\")\n",
            "        f.write(f\"TIME: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\\n\")\n",
            "        f.write(f\"{'='*80}\\n\\n\")\n",
            "        f.write(\"--- Maven Output ---\\n\")\n",
            "        f.write(compile_output + \"\\n\\n\")\n",
            "        f.write(\"--- Tool Call Log ---\\n\")\n",
            "        f.write(agent.get_log() + \"\\n\\n\")\n",
            "        f.write(\"--- Final Result ---\\n\")\n",
            "        f.write(str(result)[:3000] + \"\\n\")\n",
            "        f.write(f\"\\n---\\n\\n\")\n",
            "\n",
            "    print(\"→ Phase 2 complete. Check log.txt for detailed run history.\")\n"
        ]
    },
    # Cell 8: Final Verification & Summary
    {
        "cell_type": "markdown",
        "id": "final-verify-section-desc",
        "metadata": {},
        "source": [
            "## 3. Final Verification & Secondary Checks\n",
            "\n",
            "We verify that the whole codebase compiles successfully under JDK 17, and check remaining AST structures for libraries like Mockito."
        ]
    },
    # Cell 9: Run final clean compile
    {
        "cell_type": "code",
        "execution_count": None,
        "id": "final-verify-compile",
        "metadata": {},
        "source": [
            "# Run a final clean test compilation and execution with MavenRunner targeting Java 17 to verify all changes\n",
            "runner = MavenRunner(target_java_version=\"17\")\n",
            "print(\"Running final clean mvn test to verify all tests pass...\")\n",
            "final_test_res = runner.test(PROJECT_PATH, skip_tests=False, clean=True)\n",
            "print(f\"Test execution exit code: {final_test_res.status}\")\n",
            "\n",
            "if final_test_res.status == 0:\n",
            "    print(\"✓ Success! All unit tests pass cleanly under JDK 17 after migration.\")\n",
            "else:\n",
            "    print(\"✗ Errors encountered during test execution. Showing stdout/stderr output:\")\n",
            "    print(\"--- STDOUT ---\")\n",
            "    print(final_test_res.stdout)\n",
            "    print(\"--- STDERR ---\")\n",
            "    print(final_test_res.stderr)"
        ]
    },
    # Cell 10: AST Mockito Usage Query
    {
        "cell_type": "code",
        "execution_count": None,
        "id": "final-verify-ast",
        "metadata": {},
        "source": [
            "# Find usages of Mockito in import statements using tree-sitter AST queries in the isolated directory\n",
            "print(\"Querying AST for Mockito import declarations:\")\n",
            "mockito_imports = find_code_usages(\n",
            "    project_path=str(PROJECT_PATH),\n",
            "    node_type=\"import_declaration\",\n",
            "    identifier=\"mockito\"\n",
            ")\n",
            "\n",
            "print(f\"Found {len(mockito_imports)} Mockito import nodes:\")\n",
            "for imp in mockito_imports[:10]:\n",
            "    print(f\"  - {imp['file_path']} | Line {imp['start_line']}: {imp['snippet'].strip()}\")"
        ]
    },
    # Cell 11: Run Agent Unit Tests
    {
        "cell_type": "code",
        "execution_count": None,
        "id": "run-agent-tests",
        "metadata": {},
        "outputs": [],
        "source": [
            "# Run the python agent unit tests to verify indexer and overlap validation\n",
            "import subprocess\n",
            "import sys\n",
            "print(\"Running TranslatorAgent_2 unit tests...\")\n",
            "res = subprocess.run([sys.executable, \"tests/test_translator_agent_2_tools.py\"], capture_output=True, text=True)\n",
            "print(f\"Test exit code: {res.returncode}\")\n",
            "print(\"--- STDOUT ---\")\n",
            "print(res.stdout)\n",
            "print(\"--- STDERR ---\")\n",
            "print(res.stderr)"
        ]
    },
    # Cell 11b: Compute JaCoCo Test Coverage
    {
        "cell_type": "code",
        "execution_count": None,
        "id": "run-jacoco-coverage",
        "metadata": {},
        "outputs": [],
        "source": [
            "# Calculate test coverage using the new MavenRunner.coverage() function\n",
            "# Even if unit tests fail, Maven will continue to generate the report because we added -Dmaven.test.failure.ignore=true.\n",
            "runner = MavenRunner(target_java_version=\"17\")\n",
            "print(\"Running unit tests with JaCoCo to compute code coverage...\")\n",
            "cov_res = runner.coverage(PROJECT_PATH, clean=True)\n",
            "print(f\"Maven execution status: {cov_res.status}\")\n",
            "\n",
            "# Calculate LLM calls count from agent log\n",
            "llm_calls_count = 0\n",
            "if 'agent' in globals():\n",
            "    llm_calls_count = len(re.findall(r\"ReAct iteration \\d+/\\d+\", agent.get_log()))\n",
            "print(f\"LLM calls: {llm_calls_count}\")\n",
            "\n",
            "# Parse test pass rate\n",
            "pass_rate = 100.0\n",
            "total_tests = 0\n",
            "failed_tests = 0\n",
            "errors_tests = 0\n",
            "def parse_test_results(stdout_str):\n",
            "    if not stdout_str:\n",
            "        return 0, 0, 0\n",
            "    t_sum, f_sum, e_sum = 0, 0, 0\n",
            "    for line in stdout_str.splitlines():\n",
            "        if \"Tests run:\" in line and \" - in \" not in line:\n",
            "            match = re.search(r\"Tests run:\\s*(\\d+),\\s*Failures:\\s*(\\d+),\\s*Errors:\\s*(\\d+)\", line)\n",
            "            if match:\n",
            "                t_sum += int(match.group(1))\n",
            "                f_sum += int(match.group(2))\n",
            "                e_sum += int(match.group(3))\n",
            "    return t_sum, f_sum, e_sum\n",
            "\n",
            "stdout_to_parse = \"\"\n",
            "if 'final_test_res' in globals() and final_test_res.stdout:\n",
            "    stdout_to_parse = final_test_res.stdout\n",
            "elif cov_res.stdout:\n",
            "    stdout_to_parse = cov_res.stdout\n",
            "\n",
            "total_tests, failed_tests, errors_tests = parse_test_results(stdout_to_parse)\n",
            "if total_tests > 0:\n",
            "    pass_rate = ((total_tests - failed_tests - errors_tests) / total_tests) * 100.0\n",
            "\n",
            "print(f\"Test case pass rate: {pass_rate:.2f}% (with total: {total_tests}, failures: {failed_tests}, errors: {errors_tests})\")\n",
            "print(f\"Coverage Found: {cov_res.coverage_found}\")\n",
            "if cov_res.coverage_found:\n",
            "    print(f\"Line Coverage: {cov_res.line_coverage_pct:.2f}%\")\n",
            "    print(f\"Covered Lines: {cov_res.covered_lines}\")\n",
            "    print(f\"Missed Lines: {cov_res.missed_lines}\")\n",
            "    print(f\"Report XML location: {cov_res.jacoco_xml_path}\")\n",
            "else:\n",
            "    print(\"⚠️  Could not find or parse JaCoCo XML report!\")\n",
            "    print(\"    This usually means compile failures or severe errors — check below:\")\n",
            "    print(\"--- STDOUT ---\")\n",
            "    print(cov_res.stdout[:3000])\n",
            "    print(\"--- STDERR ---\")\n",
            "    print(cov_res.stderr[:3000])"
        ]
    },
    # Cell 12: Summary
    {
        "cell_type": "code",
        "execution_count": None,
        "id": "step2-summary",
        "metadata": {},
        "outputs": [],
        "source": [
            "print(\"=== STEP 2 MIGRATION COMPLETION SUMMARY ===\")\n",
            "print(f\"Code translation and JDK 17 migration completed in isolated folder!\")\n",
            "print(f\"The migrated codebase is preserved at: {PROJECT_PATH}\")"
        ]
    }
]

notebook = {
    "cells": cells,
    "metadata": {
        "kernelspec": {
            "display_name": "Python 3 (.venv)",
            "language": "python",
            "name": "python3"
        },
        "language_info": {
            "codemirror_mode": {
                "name": "ipython",
                "version": 3
            },
            "file_extension": ".py",
            "mimetype": "text/x-python",
            "name": "python",
            "nbconvert_exporter": "python",
            "pygments_lexer": "ipython3",
            "version": "3.12.0"
        }
    },
    "nbformat": 4,
    "nbformat_minor": 5
}

target_path = Path("translator_simulation_2.ipynb")
with open(target_path, "w", encoding="utf-8") as f:
    json.dump(notebook, f, indent=1, ensure_ascii=False)
print("Notebook translator_simulation_2.ipynb generated successfully!")
