import json
from pathlib import Path

cells = [
    # Cell 1: Intro
    {
        "cell_type": "markdown",
        "id": "intro-step2",
        "metadata": {},
        "source": [
            "# Step 2: Java Source Code Translation (Layer 2 & 3 Consolidated)\n",
            "\n",
            "This notebook simulates and prototypes the code refactoring process on the `working/sonar-stash` project codebase.\n",
            "\n",
            "This step focuses on:\n",
            "- Detecting JDK 17 deprecated/removed APIs (Layer 2) using `jdeprscan`.\n",
            "- Collecting compilation errors under JDK 17 (Layer 3) using `mvn compile`.\n",
            "- Bundling findings by file and querying local Ollama LLM to refactor using a list of non-overlapping block edits applied from bottom to top."
        ]
    },
    # Cell 2: Setup Paths and Project Root
    {
        "cell_type": "code",
        "execution_count": None,
        "id": "setup-paths-step2",
        "metadata": {},
        "outputs": [],
        "source": [
            "import sys\n",
            "import os\n",
            "import json\n",
            "from pathlib import Path\n",
            "\n",
            "# Ensure project root is in sys.path\n",
            "PROJECT_ROOT = Path.cwd().resolve()\n",
            "if str(PROJECT_ROOT) not in sys.path:\n",
            "    sys.path.append(str(PROJECT_ROOT))\n",
            "\n",
            "print(f\"Project root added to path: {PROJECT_ROOT}\")\n",
            "\n",
            "# Check availability of key imports\n",
            "from src.tools.maven import MavenProject, MavenPomEditor, MavenRunner\n",
            "from src.core.tree_sitter_engine import UniversalASTReader\n",
            "from src.tools.codebase_search_tools import find_code_usages, search_codebase\n",
            "\n",
            "print(\"Successfully imported models and tools!\")\n",
            "\n",
            "# Setup paths globally (Adjust PROJECT_PATH to point to your target Java project)\n",
            "PROJECT_PATH = Path(\"working/sonar-stash\").resolve()\n",
            "pom_path = PROJECT_PATH / \"pom.xml\"\n",
            "ARTIFACTS_DIR = PROJECT_PATH / \"artifacts\"\n",
            "\n",
            "review_file = ARTIFACTS_DIR / \"reader_review.json\"\n",
            "if not review_file.exists():\n",
            "    review_file = Path(\"dependency_focus_scopes.json\").resolve()\n",
            "\n",
            "print(f\"Working Project path: {PROJECT_PATH} (exists: {PROJECT_PATH.exists()})\")\n",
            "print(f\"Artifacts path: {ARTIFACTS_DIR}\")\n",
            "print(f\"Review report path: {review_file} (exists: {review_file.exists()})\")"
        ]
    },
    # Cell 3: Load Reports
    {
        "cell_type": "code",
        "execution_count": None,
        "id": "load-reports-step2",
        "metadata": {},
        "outputs": [],
        "source": [
            "# Load POM upgrade results from POM migration phase\n",
            "review_data = {}\n",
            "selected_sol = {}\n",
            "\n",
            "if review_file.exists():\n",
            "    with open(review_file, \"r\", encoding=\"utf-8\") as f:\n",
            "        review_data = json.load(f)\n",
            "    review_body = review_data.get(\"review_upgrade_candidates\", {})\n",
            "    selected_sol = review_body.get(\"selected_solution\", {})\n",
            "    print(\"Upgraded Dependency Mappings (from reader_review.json):\")\n",
            "    print(json.dumps(selected_sol, indent=2))\n",
            "else:\n",
            "    print(\"reader_review.json not found!\")"
        ]
    },
    # Cell 4: Markdown Section Intro
    {
        "cell_type": "markdown",
        "id": "scan-section-desc",
        "metadata": {},
        "source": [
            "## 1. Consolidated Compilation & Deprecated API Scan\n",
            "\n",
            "We run JDK 17 compilation to get modern compiler errors and execute `jdeprscan` to capture deprecated/removed API usages. These are aggregated by Java source file."
        ]
    },
    # Cell 5: Run Scan & Rule Matching
    {
        "cell_type": "code",
        "execution_count": None,
        "id": "consolidated-scan",
        "metadata": {},
        "outputs": [],
        "source": [
            "from src.tools.maven import MavenRunner, MavenProject\n",
            "from src.tools.jdeprscan_pipeline import run_jdeprscan_pipeline\n",
            "import re\n",
            "\n",
            "# 1. Compile project under JDK 17 once to extract initial compile errors\n",
            "print(\"Compiling project under JDK 17...\")\n",
            "runner = MavenRunner(target_java_version=\"17\")\n",
            "compile_res = runner.compile(PROJECT_PATH, clean=True)\n",
            "print(f\"Initial compile status: {compile_res.status}\")\n",
            "\n",
            "# 2. Run jdeprscan pipeline under JDK 17 to detect deprecated/removed APIs (Level 2)\n",
            "print(\"Running jdeprscan pipeline on the working codebase...\")\n",
            "updated_jdeprscan_result = run_jdeprscan_pipeline(\n",
            "    project_path=str(PROJECT_PATH),\n",
            "    target_release=\"17\",\n",
            "    logger=lambda msg: print(f\"  {msg}\")\n",
            ")\n",
            "\n",
            "file_findings = {}\n",
            "\n",
            "# Regex pattern to parse maven javac error details (captures relative file path, line number, error details)\n",
            "err_pattern = r\"(src[\\\\/]main[\\\\/]java[\\\\/][^\\s:\\[]+?\\.java)(?:\\[|:)?(\\d+)(?:,\\d+)?\\]?:?\\s+error:\\s+(.*)\"\n",
            "\n",
            "# Parse errors from JDK 17 compilation\n",
            "compile_errors_matched = re.findall(err_pattern, compile_res.stdout) + re.findall(err_pattern, compile_res.stderr)\n",
            "print(f\"\\nExtracted {len(compile_errors_matched)} compile error(s) under JDK 17:\")\n",
            "for rel_path, line_no, err_msg in compile_errors_matched:\n",
            "    standard_path = rel_path.replace(\"\\\\\", \"/\")\n",
            "    file_findings.setdefault(standard_path, {\"findings\": [], \"matching_rules\": []})\n",
            "    file_findings[standard_path][\"findings\"].append(f\"Compile Error (Line {line_no}): {err_msg}\")\n",
            "    print(f\"  * {standard_path}:{line_no} -> {err_msg}\")\n",
            "\n",
            "# Parse compile errors from jdeprscan b1 step (runs JDK 8 compile as part of scan pipeline)\n",
            "b1_step = updated_jdeprscan_result.get(\"steps\", {}).get(\"b1_compile\", {})\n",
            "if b1_step.get(\"status\") == \"FAIL\":\n",
            "    b1_error = b1_step.get(\"error\", \"\")\n",
            "    b1_matches = re.findall(err_pattern, b1_error)\n",
            "    for rel_path, line_no, err_msg in b1_matches:\n",
            "        standard_path = rel_path.replace(\"\\\\\", \"/\")\n",
            "        file_findings.setdefault(standard_path, {\"findings\": [], \"matching_rules\": []})\n",
            "        file_findings[standard_path][\"findings\"].append(f\"Compile Error (Line {line_no}): {err_msg}\")\n",
            "\n",
            "# Parse jdeprscan B2 project scan warnings/removal items\n",
            "b2_step = updated_jdeprscan_result.get(\"steps\", {}).get(\"b2_project_scan\", {})\n",
            "for line in b2_step.get(\"for_removal\", []) + b2_step.get(\"deprecated\", []):\n",
            "    m = re.match(r\"class\\s+([^\\s]+)\\s+uses\", line)\n",
            "    if m:\n",
            "        class_path = m.group(1)\n",
            "        rel_path = f\"src/main/java/{class_path}.java\"\n",
            "        file_findings.setdefault(rel_path, {\"findings\": [], \"matching_rules\": []})\n",
            "        file_findings[rel_path][\"findings\"].append(f\"Jdeprscan warning: {line}\")\n",
            "\n",
            "# Parse reader review flagged risks\n",
            "if review_file.exists():\n",
            "    review_body = review_data.get(\"review_upgrade_candidates\", {})\n",
            "    risks_text = review_body.get(\"risks\", \"\")\n",
            "    candidates = re.findall(r\"\\b(?:javax\\.\\w+|com\\.sun\\.\\w+)\\b\", risks_text)\n",
            "    for cand in candidates:\n",
            "        matches = search_codebase(\n",
            "            project_path=str(PROJECT_PATH),\n",
            "            regex_pattern=r\"import\\s+\" + cand.replace(\".\", r\"\\.\"),\n",
            "            file_extensions=[\"java\"]\n",
            "        )\n",
            "        for m in matches:\n",
            "            rel_path = m[\"file_path\"].replace(\"\\\\\", \"/\")\n",
            "            file_findings.setdefault(rel_path, {\"findings\": [], \"matching_rules\": []})\n",
            "            file_findings[rel_path][\"findings\"].append(f\"Reader review flagged risk: usage of {cand}\")\n",
            "\n",
            "# Deduplicate findings per file\n",
            "for path, info in file_findings.items():\n",
            "    info[\"findings\"] = list(set(info[\"findings\"]))\n",
            "\n",
            "# Load rules and match them against findings and codebase contents\n",
            "rules_file = Path(\"migration_rules.json\")\n",
            "rules = []\n",
            "if rules_file.exists():\n",
            "    with open(rules_file, \"r\", encoding=\"utf-8\") as f:\n",
            "        rules = json.load(f).get(\"rules\", [])\n",
            "\n",
            "for rel_path, info in file_findings.items():\n",
            "    full_path = PROJECT_PATH / rel_path\n",
            "    if not full_path.exists():\n",
            "        continue\n",
            "    file_content = full_path.read_text(errors=\"ignore\")\n",
            "    for rule in rules:\n",
            "        target = rule.get(\"target\")\n",
            "        if target:\n",
            "            is_match = False\n",
            "            for fnd in info[\"findings\"]:\n",
            "                if target in fnd:\n",
            "                    is_match = True\n",
            "                    break\n",
            "            if not is_match:\n",
            "                if rule.get(\"type\") == \"import_declaration\":\n",
            "                    if f\"import {target}\" in file_content:\n",
            "                        is_match = True\n",
            "                else: \n",
            "                    target_short = target.split()[-1].split(\"(\")[0]\n",
            "                    if target_short in file_content:\n",
            "                        is_match = True\n",
            "            if is_match and rule not in info[\"matching_rules\"]:\n",
            "                info[\"matching_rules\"].append(rule)\n",
            "\n",
            "print(f\"\\nFound {len(file_findings)} file(s) requiring translation:\")\n",
            "for path, info in file_findings.items():\n",
            "    print(f\"\\n- File: {path}\")\n",
            "    print(f\"  Findings:\")\n",
            "    for fnd in info[\"findings\"]:\n",
            "        print(f\"    * {fnd}\")\n",
            "    print(f\"  Matching Rules:\")\n",
            "    for r in info[\"matching_rules\"]:\n",
            "        print(f\"    * [{r.get('rule_id')}] {r.get('target')} -> {r.get('new')} ({r.get('reason')})\")\n",
            "\n",
            "# Save diagnostic reports to target/ and artifacts/ so the agent can load them\n",
            "for folder in [\"artifacts\", \"target\"]:\n",
            "    dir_path = PROJECT_PATH / folder\n",
            "    dir_path.mkdir(parents=True, exist_ok=True)\n",
            "    with open(dir_path / \"jdeprscan_report.json\", \"w\", encoding=\"utf-8\") as f:\n",
            "        json.dump(updated_jdeprscan_result, f, indent=2, default=str)\n",
            "    change_candidates = []\n",
            "    for f_path, f_info in file_findings.items():\n",
            "        change_candidates.append({\n",
            "            \"file_path\": f_path,\n",
            "            \"reason\": \"; \".join(f_info[\"findings\"]),\n",
            "            \"matching_rules\": f_info[\"matching_rules\"]\n",
            "        })\n",
            "    mygrate_report = {\n",
            "        \"status\": \"ok\",\n",
            "        \"change_candidates\": change_candidates\n",
            "    }\n",
            "    with open(dir_path / \"mygrate_report.json\", \"w\", encoding=\"utf-8\") as f:\n",
            "        json.dump(mygrate_report, f, indent=2, default=str)\n",
            "print(\"\\nSuccessfully saved jdeprscan_report.json and mygrate_report.json to target/ and artifacts/!\")\n"
        ]
    },
    # Cell 6: Markdown Translation Intro
    {
        "cell_type": "markdown",
        "id": "translation-section-desc",
        "metadata": {},
        "source": [
            "## 2. Iterative Translation Loop\n",
            "\n",
            "We run a focused code translation loop to resolve JDK 17 migration blockers file-by-file.\n",
            "For each file, we call ChatOllama directly to refactor code, apply the modified source, and check the Maven compilation status to verify correctness."
        ]
    },
    # Cell 7: Define TranslatorAgent_2 inline
    {
        "cell_type": "code",
        "execution_count": None,
        "id": "define-translator-agent-2",
        "metadata": {},
        "outputs": [],
        "source": [
            "import os\n",
            "import json\n",
            "import re\n",
            "from pathlib import Path\n",
            "from typing import Any\n",
            "from langchain_core.messages import ToolMessage\n",
            "from src.agents.base_agent import BaseAgent, ToolDefinition\n",
            "from src.tools.maven import MavenRunner\n",
            "\n",
            "class TranslatorAgent_2(BaseAgent):\n",
            "    \"\"\"\n",
            "    TranslatorAgent_2 is a lightweight, focused agent defined directly in the notebook.\n",
            "    It handles java source code migration and compilation error repair on a single file\n",
            "    by executing a ReAct loop with read, write, replace, and compile tools.\n",
            "    \"\"\"\n",
            "\n",
            "    def __init__(self, model_name: str | None = None):\n",
            "        super().__init__(model_name)\n",
            "        self.project_path = \"\"\n",
            "        self.MAX_ITERATIONS = 20\n",
            "\n",
            "    def get_system_prompt(self) -> str:\n",
            "        return (\n",
            "            \"You are an expert Java migration agent specializing in upgrading projects to JDK 17.\\n\"\n",
            "            \"Your task is to resolve compiler errors, removed JDK APIs, and deprecations in the target file.\\n\\n\"\n",
            "            \"Follow these rules strictly:\\n\"\n",
            "            \"1. First, call the `read_file` tool to inspect the content of the file.\\n\"\n",
            "            \"2. Analyze the findings and rules. Use `replace_file_content` (preferred for localized edits) or `write_file` (to overwrite) to edit the file.\\n\"\n",
            "            \"3. After modifying a file, you MUST call the `compile_project` tool to compile the project under JDK 17 and verify if there are any remaining compiler errors.\\n\"\n",
            "            \"4. Analyze the compiler error output. If there are still compilation errors in the file, use the tools to modify the file again and compile to verify.\\n\"\n",
            "            \"5. Continue this edit-compile-repair loop until the compilation error is resolved (compilation exit code: 0 or no errors in this file).\\n\"\n",
            "            \"6. You must call tools to perform edits. Do not output code blocks directly in your conversational text responses; always use tools to apply updates.\\n\"\n",
            "            \"7. Keep your conversational responses concise. When you are finished and the project compiles, state that you have completed the migration for the file.\\n\"\n",
            "        )\n",
            "\n",
            "    def run(self, instruction: str) -> str:\n",
            "        payload = self._parse_instruction(instruction)\n",
            "        self.project_path = payload.get(\"project_path\", \"\")\n",
            "        return super().run(instruction)\n",
            "\n",
            "    def _invoke_with_retry(\n",
            "        self, \n",
            "        llm_with_tools: Any,\n",
            "        messages: list,\n",
            "        tool_map: dict[str, ToolDefinition],\n",
            "        payload: dict[str, Any],\n",
            "        react_tool_results: dict[str, Any],\n",
            "    ) -> Any | None:\n",
            "        \"\"\"\n",
            "        Sanitize message history before invoking LLM.\n",
            "        Ensures read_file content is transmitted only once and placeholder in history.\n",
            "        \"\"\"\n",
            "        for i, msg in enumerate(messages):\n",
            "            if i > 0 and isinstance(msg, ToolMessage):\n",
            "                prev_msg = messages[i-1]\n",
            "                tool_calls = getattr(prev_msg, \"tool_calls\", [])\n",
            "                for tc in tool_calls:\n",
            "                    if tc.get(\"id\") == msg.tool_call_id and tc.get(\"name\") == \"read_file\":\n",
            "                        messages[i] = ToolMessage(\n",
            "                            content='\"[File Content Removed for Brevity]\"',\n",
            "                            tool_call_id=msg.tool_call_id,\n",
            "                        )\n",
            "                        break\n",
            "        return super()._invoke_with_retry(llm_with_tools, messages, tool_map, payload, react_tool_results)\n",
            "\n",
            "    def get_tools(self) -> list[ToolDefinition]:\n",
            "        return [\n",
            "            ToolDefinition(\n",
            "                name=\"read_file\",\n",
            "                description=\"Read the full content of a file. Use this first to inspect the file's current state.\",\n",
            "                func=self._tool_read_file,\n",
            "                parameters={\n",
            "                    \"type\": \"object\",\n",
            "                    \"properties\": {\n",
            "                        \"file_path\": {\n",
            "                            \"type\": \"string\",\n",
            "                            \"description\": \"Path to the Java source file relative to project root\",\n",
            "                        }\n",
            "                    },\n",
            "                    \"required\": [\"file_path\"]\n",
            "                }\n",
            "            ),\n",
            "            ToolDefinition(\n",
            "                name=\"replace_file_content\",\n",
            "                description=(\n",
            "                    \"Replace target_content with replacement_content in a file and automatically run compile. \"\n",
            "                    \"Make sure target_content matches the existing lines exactly, including indentation.\"\n",
            "                ),\n",
            "                func=self._tool_replace_file_content,\n",
            "                parameters={\n",
            "                    \"type\": \"object\",\n",
            "                    \"properties\": {\n",
            "                        \"file_path\": {\n",
            "                            \"type\": \"string\",\n",
            "                            \"description\": \"Path to the Java source file relative to project root\",\n",
            "                        },\n",
            "                        \"target_content\": {\n",
            "                            \"type\": \"string\",\n",
            "                            \"description\": \"The exact block of code to search for and replace\",\n",
            "                        },\n",
            "                        \"replacement_content\": {\n",
            "                            \"type\": \"string\",\n",
            "                            \"description\": \"The new block of code to replace target_content with\",\n",
            "                        }\n",
            "                    },\n",
            "                    \"required\": [\"file_path\", \"target_content\", \"replacement_content\"]\n",
            "                }\n",
            "            ),\n",
            "            ToolDefinition(\n",
            "                name=\"write_file\",\n",
            "                description=\"Overwrite the entire content of a file with new code and compile to verify.\",\n",
            "                func=self._tool_write_file,\n",
            "                parameters={\n",
            "                    \"type\": \"object\",\n",
            "                    \"properties\": {\n",
            "                        \"file_path\": {\n",
            "                            \"type\": \"string\",\n",
            "                            \"description\": \"Path to the Java source file relative to project root\",\n",
            "                        },\n",
            "                        \"content\": {\n",
            "                            \"type\": \"string\",\n",
            "                            \"description\": \"The complete new content of the file\",\n",
            "                        }\n",
            "                    },\n",
            "                    \"required\": [\"file_path\", \"content\"]\n",
            "                }\n",
            "            ),\n",
            "            ToolDefinition(\n",
            "                name=\"compile_project\",\n",
            "                description=\"Compile the project using Maven under JDK 17 to check for compiler errors.\",\n",
            "                func=self._tool_compile_project,\n",
            "                parameters={\n",
            "                    \"type\": \"object\",\n",
            "                    \"properties\": {},\n",
            "                    \"required\": []\n",
            "                }\n",
            "            )\n",
            "        ]\n",
            "\n",
            "    def _tool_read_file(self, file_path: str, **kwargs) -> str:\n",
            "        try:\n",
            "            path = Path(file_path)\n",
            "            if not path.is_absolute():\n",
            "                path = Path(self.project_path) / path\n",
            "            if not path.exists():\n",
            "                return f\"Error: File {file_path} does not exist.\"\n",
            "            return path.read_text(encoding=\"utf-8\")\n",
            "        except Exception as e:\n",
            "            return f\"Error reading file {file_path}: {e}\"\n",
            "\n",
            "    def _tool_compile_project(self, **kwargs) -> dict[str, Any]:\n",
            "        try:\n",
            "            runner = MavenRunner(target_java_version=\"17\")\n",
            "            compile_res = runner.compile(self.project_path, clean=True)\n",
            "            output = compile_res.stdout + \"\\n\" + compile_res.stderr\n",
            "            status = compile_res.status\n",
            "            \n",
            "            relevant_errors = self._filter_compile_errors(output)\n",
            "            return {\n",
            "                \"exit_code\": status,\n",
            "                \"success\": status == 0,\n",
            "                \"relevant_errors\": relevant_errors if relevant_errors else \"No errors found.\"\n",
            "            }\n",
            "        except Exception as e:\n",
            "            return {\"error\": f\"Failed to run compilation: {e}\"}\n",
            "\n",
            "    def _tool_replace_file_content(self, file_path: str, target_content: str, replacement_content: str, **kwargs) -> str:\n",
            "        try:\n",
            "            path = Path(file_path)\n",
            "            if not path.is_absolute():\n",
            "                path = Path(self.project_path) / path\n",
            "            if not path.exists():\n",
            "                return f\"Error: File {file_path} does not exist.\"\n",
            "            \n",
            "            content = path.read_text(encoding=\"utf-8\")\n",
            "            if target_content not in content:\n",
            "                return f\"Error: Target content not found in {file_path}. Make sure it matches exactly, including indentation.\"\n",
            "            \n",
            "            new_content = content.replace(target_content, replacement_content)\n",
            "            path.write_text(new_content, encoding=\"utf-8\")\n",
            "            \n",
            "            compile_res = self._tool_compile_project()\n",
            "            return f\"Success: Replaced content. Compilation result:\\n{json.dumps(compile_res, indent=2)}\"\n",
            "        except Exception as e:\n",
            "            return f\"Error replacing content in {file_path}: {e}\"\n",
            "\n",
            "    def _tool_write_file(self, file_path: str, content: str, **kwargs) -> str:\n",
            "        try:\n",
            "            path = Path(file_path)\n",
            "            if not path.is_absolute():\n",
            "                path = Path(self.project_path) / path\n",
            "            path.parent.mkdir(parents=True, exist_ok=True)\n",
            "            path.write_text(content, encoding=\"utf-8\")\n",
            "            \n",
            "            compile_res = self._tool_compile_project()\n",
            "            return f\"Success: Wrote file. Compilation result:\\n{json.dumps(compile_res, indent=2)}\"\n",
            "        except Exception as e:\n",
            "            return f\"Error writing file {file_path}: {e}\"\n",
            "\n",
            "    def _filter_compile_errors(self, compile_output: str) -> str:\n",
            "        lines = compile_output.split(\"\\n\")\n",
            "        relevant_lines = []\n",
            "        for line in lines:\n",
            "            if \"[ERROR]\" in line or \"error:\" in line or \"Compilation failure\" in line:\n",
            "                relevant_lines.append(line)\n",
            "        if not relevant_lines:\n",
            "            return \"\"\n",
            "        return \"\\n\".join(relevant_lines[:50])\n",
            "\n",
            "print(\"TranslatorAgent_2 class defined successfully!\")\n"
        ]
    },
    # Cell 8: Run Java Source Code Translation Loop
    {
        "cell_type": "code",
        "execution_count": None,
        "id": "translation-loop",
        "metadata": {},
        "outputs": [],
        "source": [
            "import os\n",
            "import json\n",
            "from pathlib import Path\n",
            "\n",
            "print(\"=== STARTING DEDICATED CODE TRANSLATION LOOP ===\")\n",
            "\n",
            "# Iterate through each file requiring translation\n",
            "print(f\"Files requiring translation: {list(file_findings.keys())}\")\n",
            "\n",
            "for rel_path, info in file_findings.items():\n",
            "    file_path = PROJECT_PATH / rel_path\n",
            "    if not file_path.exists():\n",
            "        print(f\"[WARNING] File does not exist: {file_path}\")\n",
            "        continue\n",
            "        \n",
            "    print(f\"\\n--- Translating File: {rel_path} ---\")\n",
            "    \n",
            "    findings_str = \"\\n\".join([f\"- {f}\" for f in info[\"findings\"]])\n",
            "    rules_str = \"\\n\".join([\n",
            "        f\"- [{r.get('rule_id')}] Replace '{r.get('target')}' with '{r.get('new')}' (Reason: {r.get('reason')})\"\n",
            "        for r in info[\"matching_rules\"]\n",
            "    ])\n",
            "    \n",
            "    payload = {\n",
            "        \"project_path\": str(PROJECT_PATH),\n",
            "        \"target_java_version\": \"17\",\n",
            "        \"current_instruction\": f\"Migrate the file {rel_path} to JDK 17, resolving all deprecations and compile errors.\",\n",
            "        \"findings\": findings_str,\n",
            "        \"rules\": rules_str\n",
            "    }\n",
            "    \n",
            "    agent = TranslatorAgent_2()\n",
            "    agent.run(json.dumps(payload, ensure_ascii=False, indent=2))\n"
        ]
    },
    # Cell 8: Final Verification & Summary
    {
        "cell_type": "markdown",
        "id": "final-verify-section-desc",
        "metadata": {},
        "source": [
            "## 3. Final Verification & Secondary Checks\n",
            "\n",
            "We verify that the whole codebase compiles successfully under JDK 17, and check remaining AST structures for libraries like Mockito."
        ]
    },
    # Cell 9: Run final clean compile
    {
        "cell_type": "code",
        "execution_count": None,
        "id": "final-verify-compile",
        "metadata": {},
        "source": [
            "# Run a final clean compilation with MavenRunner targeting Java 17 to verify all changes\n",
            "runner = MavenRunner(target_java_version=\"17\")\n",
            "print(\"Running final clean mvn compile to verify project state...\")\n",
            "res = runner.compile(PROJECT_PATH, clean=True)\n",
            "print(f\"Compilation exit code: {res.status}\")\n",
            "\n",
            "if res.status == 0:\n",
            "    print(\"Success! The project compiles cleanly under JDK 17 after translation and upgrades.\")\n",
            "else:\n",
            "    print(\"Errors encountered during compile. Showing stdout/stderr output:\")\n",
            "    print(\"--- STDOUT ---\")\n",
            "    print(res.stdout)\n",
            "    print(\"--- STDERR ---\")\n",
            "    print(res.stderr)"
        ]
    },
    # Cell 10: AST Mockito Usage Query
    {
        "cell_type": "code",
        "execution_count": None,
        "id": "final-verify-ast",
        "metadata": {},
        "source": [
            "# Find usages of Mockito in import statements using tree-sitter AST queries in the isolated directory\n",
            "print(\"Querying AST for Mockito import declarations:\")\n",
            "mockito_imports = find_code_usages(\n",
            "    project_path=str(PROJECT_PATH),\n",
            "    node_type=\"import_declaration\",\n",
            "    identifier=\"mockito\"\n",
            ")\n",
            "\n",
            "print(f\"Found {len(mockito_imports)} Mockito import nodes:\")\n",
            "for imp in mockito_imports[:10]:\n",
            "    print(f\"  - {imp['file_path']} | Line {imp['start_line']}: {imp['snippet'].strip()}\")"
        ]
    },
    # Cell 11: Summary
    {
        "cell_type": "code",
        "execution_count": None,
        "id": "step2-summary",
        "metadata": {},
        "outputs": [],
        "source": [
            "print(\"=== STEP 2 MIGRATION COMPLETION SUMMARY ===\")\n",
            "print(f\"Code translation and JDK 17 migration completed in isolated folder!\")\n",
            "print(f\"The migrated codebase is preserved at: {PROJECT_PATH}\")"
        ]
    }
]

notebook = {
    "cells": cells,
    "metadata": {
        "kernelspec": {
            "display_name": "Python 3 (.venv)",
            "language": "python",
            "name": "python3"
        },
        "language_info": {
            "codemirror_mode": {
                "name": "ipython",
                "version": 3
            },
            "file_extension": ".py",
            "mimetype": "text/x-python",
            "name": "python",
            "nbconvert_exporter": "python",
            "pygments_lexer": "ipython3",
            "version": "3.12.0"
        }
    },
    "nbformat": 4,
    "nbformat_minor": 5
}

target_path = Path("translator_simulation_2.ipynb")
with open(target_path, "w", encoding="utf-8") as f:
    json.dump(notebook, f, indent=1, ensure_ascii=False)
print("Notebook translator_simulation_2.ipynb generated successfully!")
