import json
from pathlib import Path

notebook_path = Path("translator_simulation_2.ipynb")
if not notebook_path.exists():
    print(f"Error: {notebook_path} does not exist!")
    exit(1)

with open(notebook_path, "r", encoding="utf-8") as f:
    data = json.load(f)

# Find the cell that contains "err_pattern" or "errors_by_file"
found_cell = False
for cell in data.get("cells", []):
    if cell.get("cell_type") == "code":
        source = cell.get("source", [])
        source_str = "".join(source)
        if "err_pattern =" in source_str or "errors_by_file = {}" in source_str:
            print("Found target cell!")
            # Let's replace the source lines
            # We want to replace everything in the "else:" block of Phase 1
            # Let's locate the "else:" block and the end of it.
            # We'll just define the entire cell's source code to be correct, clean, and robust!
            new_source = [
                "import json\n",
                "import re\n",
                "from pathlib import Path\n",
                "from datetime import datetime\n",
                "\n",
                "LOG_FILE = Path(\"log.txt\")\n",
                "\n",
                "# ── PHASE 1: Compile first to get REAL errors ──\n",
                "# We no longer do a \"blind fix\" phase because jdeprscan B1 errors from JDK 8\n",
                "# can report \"package does not exist\" for packages that DO exist in the target API.\n",
                "# Instead, we compile under JDK 17 first and use those real errors.\n",
                "print(\"=\" * 80)\n",
                "print(\"PHASE 1: Compile under JDK 17 to get real errors\")\n",
                "print(\"=\" * 80)\n",
                "\n",
                "from src.tools.maven import MavenRunner\n",
                "runner = MavenRunner(target_java_version=\"17\")\n",
                "compile_res = runner.compile(PROJECT_PATH, clean=True)\n",
                "compile_output = compile_res.stdout + \"\\n\" + compile_res.stderr\n",
                "\n",
                "print(f\"\\nCompile exit code: {compile_res.status}\")\n",
                "if compile_res.status == 0:\n",
                "    print(\"✓ Project already compiles! No migration needed.\")\n",
                "    errors_by_file = {}\n",
                "else:\n",
                "    # Parse compile errors without using fragile regex for file paths\n",
                "    errors_by_file = {}\n",
                "    for line in compile_output.splitlines():\n",
                "        if \"[ERROR]\" in line and \".java\" in line:\n",
                "            parts = line.split(\".java\")\n",
                "            if len(parts) >= 2:\n",
                "                path_part = parts[0].strip()\n",
                "                if path_part.startswith(\"[ERROR]\"):\n",
                "                    path_part = path_part[len(\"[ERROR]\"):].strip()\n",
                "                if path_part.startswith(\"/\") and len(path_part) > 2 and path_part[2] == \":\":\n",
                "                    path_part = path_part[1:]\n",
                "                \n",
                "                abs_path = Path(path_part + \".java\")\n",
                "                try:\n",
                "                    rel_path = abs_path.relative_to(PROJECT_PATH)\n",
                "                except ValueError:\n",
                "                    rel_path = abs_path\n",
                "                \n",
                "                filepath = str(rel_path).replace(\"\\\\\", \"/\")\n",
                "                details = parts[1].strip()\n",
                "                \n",
                "                line_match = re.search(r'\\d+', details)\n",
                "                line_no = line_match.group(0) if line_match else \"unknown\"\n",
                "                \n",
                "                msg = details\n",
                "                if msg.startswith(\":\"):\n",
                "                    msg = msg[1:].strip()\n",
                "                if msg.startswith(\"[\") and \"]\" in msg:\n",
                "                    msg = msg.split(\"]\", 1)[1].strip()\n",
                "                if line_no != \"unknown\" and msg.startswith(line_no):\n",
                "                    msg = msg[len(line_no):].strip()\n",
                "                if msg.startswith(\":\"):\n",
                "                    msg = msg[1:].strip()\n",
                "                if msg.lower().startswith(\"error:\"):\n",
                "                    msg = msg[6:].strip()\n",
                "                if msg.startswith(\":\"):\n",
                "                    msg = msg[1:].strip()\n",
                "                \n",
                "                errors_by_file.setdefault(filepath, []).append(f\"Compile Error (Line {line_no}): {msg}\")\n",
                "\n",
                "    # Deduplicate\n",
                "    for f, errs in errors_by_file.items():\n",
                "        errors_by_file[f] = list(set(errs))\n",
                "\n",
                "    print(f\"Found {sum(len(v) for v in errors_by_file.values())} error(s) in {len(errors_by_file)} file(s):\")\n",
                "    for f, errs in errors_by_file.items():\n",
                "        print(f\"  {f}: {len(errs)} error(s)\")\n",
                "\n",
                "# ── PHASE 2: Fix each file with compile errors using the agent ──\n",
                "if errors_by_file:\n",
                "    print(\"\\n\" + \"=\" * 80)\n",
                "    print(\"PHASE 2: Iterative Fix — fix each file with errors, then verify\")\n",
                "    print(\"=\" * 80)\n",
                "\n",
                "    phase2_results = {}\n",
                "\n",
                "    for rel_path_err, errs in errors_by_file.items():\n",
                "        file_path = PROJECT_PATH / rel_path_err\n",
                "        if not file_path.exists():\n",
                "            print(f\"[WARNING] File does not exist: {file_path}\")\n",
                "            continue\n",
                "\n",
                "        print(f\"\\n--- Fixing: {rel_path_err} ({len(errs)} error(s)) ---\")\n",
                "\n",
                "        findings_str = \"\\n\".join([f\"- {e}\" for e in errs])\n",
                "        payload = {\n",
                "            \"project_path\": str(PROJECT_PATH),\n",
                "            \"target_java_version\": \"17\",\n",
                "            \"current_instruction\": (\n",
                "                f\"Fix the compile errors in {rel_path_err}. \"\n",
                "                f\"Read the file first, then call check_class on any import you plan to remove. \"\n",
                "                f\"Apply all fixes using apply_edits, then call compile_project to verify. \"\n",
                "                f\"Keep fixing until this file compiles or you've tried your best.\"\n",
                "            ),\n",
                "            \"findings\": findings_str,\n",
                "            \"rules\": \"\"\n",
                "        }\n",
                "\n",
                "        agent = TranslatorAgent_2()\n",
                "        result = agent.run(json.dumps(payload, ensure_ascii=False, indent=2))\n",
                "\n",
                "        # Log phase 2\n",
                "        with open(LOG_FILE, \"a\", encoding=\"utf-8\") as f:\n",
                "            f.write(f\"\\n{'='*80}\\n\")\n",
                "            f.write(f\"PHASE 2 — FIX: {rel_path_err}\\n\")\n",
                "            f.write(f\"TIME: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\\n\")\n",
                "            f.write(f\"{'='*80}\\n\\n\")\n",
                "            f.write(\"--- Compile Errors ---\\n\")\n",
                "            f.write(findings_str + \"\\n\\n\")\n",
                "            f.write(\"--- Tool Call Log ---\\n\")\n",
                "            f.write(agent.get_log() + \"\\n\\n\")\n",
                "            f.write(\"--- Final Result ---\\n\")\n",
                "            f.write(str(result)[:3000] + \"\\n\")\n",
                "            f.write(f\"\\n---\\n\\n\")\n",
                "\n",
                "        phase2_results[rel_path_err] = result\n",
                "        print(f\"  → Phase 2 complete for {rel_path_err}\")\n",
                "\n",
                "    # ── PHASE 3: Final verification compile ──\n",
                "    print(\"\\n\" + \"=\" * 80)\n",
                "    print(\"PHASE 3: Final Verification — Whole-Project Compile\")\n",
                "    print(\"=\" * 80)\n",
                "\n",
                "    final_res = runner.compile(PROJECT_PATH, clean=True)\n",
                "    print(f\"\\nFinal compile exit code: {final_res.status}\")\n",
                "    if final_res.status == 0:\n",
                "        print(\"✓ Project compiles successfully after all fixes!\")\n",
                "    else:\n",
                "        final_output = final_res.stdout + \"\\n\" + final_res.stderr\n",
                "        final_errors = [line for line in final_output.split(\"\\n\")\n",
                "                        if \"[ERROR]\" in line or \"error:\" in line]\n",
                "        print(f\"  {len(final_errors)} error(s) remain:\")\n",
                "        for line in final_errors[:30]:\n",
                "            print(f\"  {line}\")\n",
                "\n",
                "    with open(LOG_FILE, \"a\", encoding=\"utf-8\") as f:\n",
                "        f.write(f\"\\n{'='*80}\\n\")\n",
                "        f.write(f\"PHASE 3 — FINAL VERIFICATION\\n\")\n",
                "        f.write(f\"TIME: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\\n\")\n",
                "        f.write(f\"{'='*80}\\n\\n\")\n",
                "        f.write(f\"Exit code: {final_res.status}\\n\")\n",
                "        if final_res.status != 0:\n",
                "            f.write(\"\\n--- Remaining Errors ---\\n\")\n",
                "            f.write(\"\\n\".join(final_errors[:50]) + \"\\n\")\n",
                "        else:\n",
                "            f.write(\"✓ Project compiles successfully!\\n\")\n",
                "\n",
                "print(f\"\\n{'='*80}\")\n",
                "print(f\"TRANSLATION COMPLETE. Full log at: {LOG_FILE.resolve()}\")\n",
                "print(f\"{'='*80}\")"
            ]
            cell["source"] = new_source
            found_cell = True
            break

if found_cell:
    with open(notebook_path, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=1, ensure_ascii=False)
    print("Successfully updated translator_simulation_2.ipynb!")
else:
    print("Target cell not found!")
